# Generated by Django 4.2.1 on 2023-05-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='customer_created',
            field=models.BooleanField(default=False),
        ),
    ]
