# Generated by Django 4.2.1 on 2023-05-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_phone_user_mobile_user_customer_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
