# Generated by Django 3.2.19 on 2023-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_ticket',
            name='Customer_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Customer_id',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='processed',
            new_name='is_closed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='post_ticket',
        ),
    ]
